---
abstract: 'Color output using ANSI escape sequences'
author:
  - 'Russ Allbery <rra@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.28'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Term-ANSIColor
provides:
  Term::ANSIColor:
    file: lib/Term/ANSIColor.pm
    version: '4.03'
requires:
  perl: '5.006'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Term-ANSIColor
  license: http://dev.perl.org/licenses/
  repository: git://git.eyrie.org/perl/ansicolor.git
version: '4.03'
